name: Vagrant
on: [push, pull_request]

jobs:

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Install Vagrant
      #   run: |
      #     brew tap
      #     brew install hashicorp/tap/hashicorp-vagrant


      # - name: Install VirtualBox
      #   run: |
      #     brew update
      #     brew tap homebrew/cask
      #     brew install --cask virtualbox
      #     brew cleanup
      - name: Create environment file
        run: |
          mv ./back/dotenv-back-example ./back/.env

      # - name: Vagrant automation permissions
      #   run: |
      #     sudo cp ./back/macos-autosmb /etc/sudoers.d/vagrant-syncedfolders
      #     sudo chmod -R 0440 /etc/sudoers.d
      #     sudo visudo -c
          
      - name: Add box
        run: |
          vagrant box add bento/ubuntu-22.04 --provider virtualbox
          sudo vagrant plugin install vagrant-scp
      
      - name: Vagrant up
        run: |
          cd back
          export COMPOSE_PROFILES=redis,rabbitmq,celery
          export numberOfBoxes=1
          #echo $(vboxmanage --version)
          #VBoxManage list runningvms
          #vagrant global-status | awk '/running/{print $1}' | xargs -r -d '\n' -n 1 -- vagrant suspen
          #vagrant halt vbox1
          vagrant up vbox1
          vagrant global-status
          vagrant ssh vbox1 -c "cd /home && ls -l ."
          sudo vagrant scp $(pwd) /home/vagrant/

      - name: Checking the container
        run: |
          vagrant global-status
          cd back
          export numberOfBoxes=1
          vagrant ssh vbox1 -c "cd /home/vagrant && docker compose -f docker-compose.staging.yml up -d --build"
          vagrant ssh vbox1 -c "cd /home/vagrant && docker exec -it celery bash"
