name: Vagrant
on: [push, pull_request]

jobs:

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Install Vagrant
      #   run: |
      #     uname -a
      #     brew tap
      #     brew install hashicorp/tap/hashicorp-vagrant
      #     vagrant plugin install vagrant-docker-compose
      #     brew install --cask vagrant-vmware-utility
      #     vagrant plugin install vagrant-vmware-desktop
      #     brew install --cask vmware-fusion
      #     sudo ln -s /Applications/VMWare\ Fusion\ Tech\ Preview.app /Applications/VMWare\ Fusion.app
      #     sudo /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility certificate generate
      #     #sudo /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility service install
      #     sudo launchctl load -w /Library/LaunchDaemons/com.vagrant.vagrant-vmware-utility.plist
      #     #sudo /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility api -debug
      #     #sudo mkdir -p /opt/vagrant-vmware-desktop/bin
      #     #sudo unzip -d /opt/vagrant-vmware-desktop/bin vagrant-vmware-utility_1.0.0_linux_amd64.zip
          

      - name: Install VirtualBox
        run: |
          brew update
          brew tap homebrew/cask
          brew install --cask virtualbox
          brew cleanup
          
      - name: Create environment file
        run: |
          mv ./back/dotenv-back-example ./back/.env

      - name: Vagrant automation permissions
        run: |
          sudo cp ./back/macos-autosmb /etc/sudoers.d/vagrant-syncedfolders
          sudo chmod -R 0440 /etc/sudoers.d
          sudo visudo -c
          
      - name: Add box
        run: |
          vagrant box add bento/ubuntu-22.04 --provider virtualbox

      
      - name: Vagrant up
        run: |
          cd back
          export COMPOSE_PROFILES=redis,rabbitmq,celery
          export numberOfBoxes=1
          vagrant up --debug vbox1

      - name: Checking the container
        run: |
          vagrant ssh vbox1
          docker exec -it celery bash
