name: Vagrant

on: [push, pull_request]

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vagrant
        run: |
          sudo apt-get install -y wget
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install -y vagrant
          vagrant plugin install vagrant-docker-compose
        shell: bash

      # - name: Install VirtualBox
      #   run: |
      #     brew update
      #     brew tap homebrew/cask
      #     brew install --cask virtualbox
      #     brew cleanup
          
      # - name: Create environment file
      #   run: |
      #     mv ./back/dotenv-back-example ./back/.env

      # - name: Vagrant automation permissions
      #   run: |
      #     sudo cp ./back/macos-autosmb /etc/sudoers.d/vagrant-syncedfolders
      #     sudo chmod -R 0440 /etc/sudoers.d
      #     sudo visudo -c
          
      # - name: Add box
      #   run: |
      #     vagrant box add bento/ubuntu-22.04 --provider virtualbox
      
      # - name: Vagrant up
      #   run: |
      #     cd back
      #     export COMPOSE_PROFILES=redis,rabbitmq,celery
      #     export numberOfBoxes=1
      #     vagrant up vbox1

      # - name: Checking the container
      #   run: |
      #     vagrant ssh vbox1
      #     docker exec -it celery bash
